language: zh-TW

players:
  - name: DemoPlayer1
    model: demo

  - name: DemoPlayer2
    model: demo

  - name: DemoPlayer3
    model: demo

  - name: DemoPlayer4
    model: demo

  - name: DemoPlayer5
    model: demo

  - name: DemoPlayer6
    model: demo

  - name: DemoPlayer7
    model: demo

  - name: DemoPlayer8
    model: demo

  - name: DemoPlayer9
    model: demo

  - name: DemoPlayer10
    model: demo

  - name: DemoPlayer11
    model: demo

  - name: DemoPlayer12
    model: demo

  - name: DemoPlayer13
    model: demo

  - name: DemoPlayer14
    model: demo

  - name: DemoPlayer15
    model: demo

  - name: DemoPlayer16
    model: demo
