# Simple 9-player configuration for LLM Werewolf
# Copy this file and customize it to your needs

preset: 9-players

players:
  - name: gpt-4o
    provider: openai
    model: gpt-4o
    api_key_env: OPENAI_API_KEY

  - name: gpt-4.1
    provider: openai
    model: gpt-4.1
    api_key_env: OPENAI_API_KEY

  - name: gpt-5
    provider: openai
    model: gpt-5
    api_key_env: OPENAI_API_KEY

  - name: gpt-5-chat
    provider: openai
    model: gpt-5-chat
    api_key_env: OPENAI_API_KEY

  - name: claude-sonnet-4-5-20250929
    provider: anthropic
    model: claude-sonnet-4-5-20250929
    api_key_env: ANTHROPIC_API_KEY

  - name: deepseek-reasoner
    provider: openai
    model: deepseek-reasoner
    api_key_env: OPENAI_API_KEY

  - name: claude-haiku-4-5-20251001
    provider: anthropic
    model: claude-haiku-4-5-20251001
    api_key_env: ANTHROPIC_API_KEY

  - name: human
    provider: human

  - name: human
    provider: human
