preset: "9-players"

players:
  - name: "GPT-4 Detective"
    model: gpt-4
    base_url: https://api.openai.com/v1
    api_key_env: OPENAI_API_KEY
    temperature: 0.7
    max_tokens: 500

  - name: "Claude Analyst"
    model: claude-3-5-sonnet-20241022
    base_url: https://api.anthropic.com/v1
    api_key_env: ANTHROPIC_API_KEY
    temperature: 0.8
    max_tokens: 600

  - name: "GPT-3.5 Scout"
    model: gpt-3.5-turbo
    base_url: https://api.openai.com/v1
    api_key_env: OPENAI_API_KEY
    temperature: 0.6
    max_tokens: 400

  - name: "Llama Local"
    model: llama3
    base_url: http://localhost:11434/v1
    temperature: 0.7
    max_tokens: 500

  - name: "Grok Thinker"
    model: grok-beta
    base_url: https://api.x.ai/v1
    api_key_env: XAI_API_KEY
    temperature: 0.7
    max_tokens: 500

  - name: "Claude Guardian"
    model: claude-3-5-sonnet-20241022
    base_url: https://api.anthropic.com/v1
    api_key_env: ANTHROPIC_API_KEY
    temperature: 0.5
    max_tokens: 400

  - name: "Human Player 1"
    model: human

  - name: "Random Bot"
    model: demo

  - name: "Human Player 2"
    model: human
