preset: 6-players
language: zh-TW

players:
  - name: gpt-5-mini
    model: gpt-5-mini
    base_url: https://api.mai0313.com
    api_key_env: OPENAI_API_KEY
    temperature: 0.7
    max_tokens: null

  - name: gpt-5-mini-1
    model: gpt-5-mini
    base_url: https://api.mai0313.com
    api_key_env: OPENAI_API_KEY
    temperature: 0.7
    max_tokens: null

  - name: gpt-5-mini-2
    model: gpt-5-mini
    base_url: https://api.mai0313.com
    api_key_env: OPENAI_API_KEY
    temperature: 0.7
    max_tokens: null

  - name: gpt-5-mini-3
    model: gpt-5-mini
    base_url: https://api.mai0313.com
    api_key_env: OPENAI_API_KEY
    temperature: 0.7
    max_tokens: null

  - name: gpt-5-mini-4
    model: gpt-5-mini
    base_url: https://api.mai0313.com
    api_key_env: OPENAI_API_KEY
    temperature: 0.7
    max_tokens: null

  - name: gpt-5-chat
    model: gpt-5-chat
    base_url: https://api.mai0313.com
    api_key_env: OPENAI_API_KEY
    temperature: 0.7
    max_tokens: null
