preset: 6-players
language: zh-TW

players:
  - name: gpt-4.1
    model: gpt-4.1
    base_url: https://api.mai0313.com
    api_key_env: OPENAI_API_KEY
    temperature: 0.7
    max_tokens: null

  - name: gpt-4.1-1
    model: gpt-4.1
    base_url: https://api.mai0313.com
    api_key_env: OPENAI_API_KEY
    temperature: 0.7
    max_tokens: null

  - name: gpt-4.1-2
    model: gpt-4.1
    base_url: https://api.mai0313.com
    api_key_env: OPENAI_API_KEY
    temperature: 0.7
    max_tokens: null

  - name: gpt-4.1-3
    model: gpt-4.1
    base_url: https://api.mai0313.com
    api_key_env: OPENAI_API_KEY
    temperature: 0.7
    max_tokens: null

  - name: gpt-4.1-4
    model: gpt-4.1
    base_url: https://api.mai0313.com
    api_key_env: OPENAI_API_KEY
    temperature: 0.7
    max_tokens: null

  - name: gpt-4.1-5
    model: gpt-4.1
    base_url: https://api.mai0313.com
    api_key_env: OPENAI_API_KEY
    temperature: 0.7
    max_tokens: null
