preset: 12-players
language: zh-TW

players:
  - name: gpt-5-chat
    model: gpt-5-chat
    base_url: https://api.mai0313.com
    api_key_env: OPENAI_API_KEY
    temperature: 0.7
    max_tokens: null

  - name: gpt-5-chat-1
    model: gpt-5-chat
    base_url: https://api.mai0313.com
    api_key_env: OPENAI_API_KEY
    temperature: 0.7
    max_tokens: null

  - name: gpt-5-chat-2
    model: gpt-5-chat
    base_url: https://api.mai0313.com
    api_key_env: OPENAI_API_KEY
    temperature: 0.7
    max_tokens: null

  - name: gpt-5-chat-3
    model: gpt-5-chat
    base_url: https://api.mai0313.com
    api_key_env: OPENAI_API_KEY
    temperature: 0.7
    max_tokens: null

  - name: gpt-5-chat-4
    model: gpt-5-chat
    base_url: https://api.mai0313.com
    api_key_env: OPENAI_API_KEY
    temperature: 0.7
    max_tokens: null

  - name: gpt-5-chat-5
    model: gpt-5-chat
    base_url: https://api.mai0313.com
    api_key_env: OPENAI_API_KEY
    temperature: 0.7
    max_tokens: null

  - name: gpt-5-chat-6
    model: gpt-5-chat
    base_url: https://api.mai0313.com
    api_key_env: OPENAI_API_KEY
    temperature: 0.7
    max_tokens: null

  - name: gpt-5-chat-7
    model: gpt-5-chat
    base_url: https://api.mai0313.com
    api_key_env: OPENAI_API_KEY
    temperature: 0.7
    max_tokens: null

  - name: gpt-5-chat-8
    model: gpt-5-chat
    base_url: https://api.mai0313.com
    api_key_env: OPENAI_API_KEY
    temperature: 0.7
    max_tokens: null

  - name: gpt-5-chat-9
    model: gpt-5-chat
    base_url: https://api.mai0313.com
    api_key_env: OPENAI_API_KEY
    temperature: 0.7
    max_tokens: null

  - name: gpt-5-chat-10
    model: gpt-5-chat
    base_url: https://api.mai0313.com
    api_key_env: OPENAI_API_KEY
    temperature: 0.7
    max_tokens: null

  - name: gpt-5-chat-11
    model: gpt-5-chat
    base_url: https://api.mai0313.com
    api_key_env: OPENAI_API_KEY
    temperature: 0.7
    max_tokens: null
